language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: HSTsaFXrXYt0pHTGaV3Eq+jf2w2O9ZyH444fHwae5dU0xi0mibzkMYpH8O0ujDF1PcA69iHGSkqk/0dBFvdhm3eR96tXCDuC4Sdzr57lJUxgz4LygveOHoMIiDbPsJTjMDkewF2iE14wliMTMUBKL6sxwF+MdOri2n839Fzf57pCwPXvH8XsvGjlEeJ5R5T8UHX3kHUkTiFpY9fj5QFutaySQ45sYeBImgVInpXQutfXNOEtgI5xqkkLxbk1+BOyZIds1AcPTq8xhE+zfGDNwnktl6RVUNSi3FjUUPJT3YF1WaRoY0UGOyTDhlXkiDFQm9zmPPbTxQRMusux8bo1tlym0dftZc/QGppoovsP846+eyY3U87UMc9+hP6qozoM2DDG3/KJc2AGnh243mel2zCLrHj24cfe+dxc0kHHRoK5K42sDwAsPSE7LigIk5tadvfxNqK5klS2h6ubm7uEtLAKZR0TD/D922DEpa7CiA5TZT4DGvHXAFkSyh023F83v1eFV4lUykmYg5nezB4mVtdVGHAj4cvBjwPE19VyWdI2BsAAJalpqRbZXYaXv59HCyI273YBKpXFfEJAlTqObU6x0vgZkleUvOReJjfimSpWAJlKlRHJQ1Z/oRktVKIWfQe/hI/PqaZqohY+QztamyQbfVo+0CDrbRaNWicsn34=
  app: gentle-river-11357
  on:
    repo: Ddoty89/gym-buddy-backend
